---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pocketmine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pocketmine.name" . }}
    helm.sh/chart: {{ include "pocketmine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pocketmine.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pocketmine.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- if .Values.persistence.enabled }}
      initContainers:
        - name: grab-pocketmine
          image: "busybox:1.30.0"
          imagePullPolicy: "Always"
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "test -f /data/pocketmine.yml || wget -O /data/pocketmine.yml https://raw.githubusercontent.com/crscheid/pocketmine-mp/master/pocketmine.yml"]
          volumeMounts:
          - name: data
            mountPath: /data
        - name: grab-server-properties
          image: "busybox:1.30.0"
          imagePullPolicy: "Always"
          securityContext:
            runAsUser: 0
          command: ["sh", "-c", "test -f /data/server.properties || wget -O server.properties https://raw.githubusercontent.com/crscheid/pocketmine-mp/master/server.properties"]
          volumeMounts:
          - name: data
            mountPath: /data
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: server
              containerPort: 19132
              protocol: UDP
#          livenessProbe:
#            udpSocket:
#              port: server
#          readinessProbe:
#            udpSocket:
#              port: server
          volumeMounts:
          - name: data
            mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "pocketmine.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
